version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: jobportal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: jobportal-redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: jobportal-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/job_portal
      - JWT_SECRET=my_super_secure_secret_key_123
      - REDIS_HOST=jobportal-redis
      - REDIS_PORT=6379
      - JWT_EXPIRES_IN=1d

  frontend:
    build: ./frontend
    container_name: jobportal-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
